export const COLORS = {
  primary: '#E53935',        // Main Red
  primaryDark: '#B71C1C',    // Dark Red
  primaryLight: '#FFEBEE',   // Light Red

  secondary: '#000000',      // Black
  accent: '#FF5252',         // Bright Red
  accentOrange: '#FF3D00',   // Deep Orange Red

  bg: '#FFFFFF',             // White Background
  white: '#FFFFFF',

  card: '#F9F9F9',           // Light Card

  text: '#000000',           // Main Text Black
  textSecondary: '#555555',  
  textLight: '#9CA3AF',

  border: '#E5E7EB',

  success: '#10B981',
  warning: '#F59E0B',
  error: '#E53935',

  star: '#FBBF24',

  gradient1: '#E53935',      // Red Gradient
  gradient2: '#000000',      // Black Gradient
};

export const courses = [
  {
    id: '1',
    title: 'Complete Physics for JEE Advanced 2025',
    instructor: 'Dr. Nitin Vijay',
    instructorAvatar: 'https://i.pravatar.cc/150?img=11',
    thumbnail: 'https://picsum.photos/seed/physics/400/220',
    rating: 4.8,
    reviews: 12400,
    price: 2999,
    originalPrice: 5999,
    enrolled: 84500,
    category: 'Physics',
    level: 'Advanced',
    duration: '180 hrs',
    lectures: 420,
    description: 'Master Physics concepts for JEE Advanced with in-depth theory, problem solving, and test series.',
    skills: ['Mechanics', 'Electrostatics', 'Optics', 'Modern Physics', 'Thermodynamics'],
    isBestseller: true,
    progress: 0,
    language: 'Hindi + English',
    lastUpdated: 'Nov 2024',
    modules: [
      { id: 'm1', title: 'Mechanics', lectures: 42, duration: '28 hrs', expanded: false, items: ['Kinematics', 'Newton\'s Laws', 'Work & Energy', 'Rotational Motion'] },
      { id: 'm2', title: 'Waves & SHM', lectures: 28, duration: '18 hrs', expanded: false, items: ['Simple Harmonic Motion', 'Wave Motion', 'Sound Waves'] },
      { id: 'm3', title: 'Electrostatics', lectures: 36, duration: '24 hrs', expanded: false, items: ['Coulomb\'s Law', 'Electric Field', 'Capacitors'] },
    ],
  },
  {
    id: '2',
    title: 'Mathematics Masterclass: Calculus to Algebra',
    instructor: 'Anand Kumar',
    instructorAvatar: 'https://i.pravatar.cc/150?img=15',
    thumbnail: 'https://picsum.photos/seed/math/400/220',
    rating: 4.9,
    reviews: 18200,
    price: 3499,
    originalPrice: 6999,
    enrolled: 120000,
    category: 'Mathematics',
    level: 'Intermediate',
    duration: '210 hrs',
    lectures: 510,
    description: 'Comprehensive Mathematics covering all topics from Class 11-12 and beyond for competitive exams.',
    skills: ['Calculus', 'Algebra', 'Coordinate Geometry', 'Trigonometry', 'Statistics'],
    isBestseller: true,
    progress: 35,
    language: 'Hindi + English',
    lastUpdated: 'Oct 2024',
    modules: [
      { id: 'm1', title: 'Algebra', lectures: 52, duration: '34 hrs', expanded: false, items: ['Quadratic Equations', 'Sequences', 'Complex Numbers', 'Matrices'] },
      { id: 'm2', title: 'Calculus', lectures: 68, duration: '45 hrs', expanded: false, items: ['Limits', 'Derivatives', 'Integration', 'Differential Equations'] },
    ],
  },
  {
    id: '3',
    title: 'Chemistry Complete Course for NEET 2025',
    instructor: 'Dr. Pradeep Sharma',
    instructorAvatar: 'https://i.pravatar.cc/150?img=20',
    thumbnail: 'https://picsum.photos/seed/chem/400/220',
    rating: 4.7,
    reviews: 9800,
    price: 2499,
    originalPrice: 4999,
    enrolled: 67000,
    category: 'Chemistry',
    level: 'Advanced',
    duration: '160 hrs',
    lectures: 380,
    description: 'Full syllabus Chemistry for NEET aspirants with organic, inorganic and physical chemistry.',
    skills: ['Organic Chemistry', 'Inorganic Chemistry', 'Physical Chemistry', 'Reaction Mechanisms'],
    isBestseller: false,
    progress: 72,
    language: 'Hindi + English',
    lastUpdated: 'Dec 2024',
    modules: [
      { id: 'm1', title: 'Physical Chemistry', lectures: 45, duration: '30 hrs', expanded: false, items: ['Atomic Structure', 'Chemical Bonding', 'Thermodynamics'] },
    ],
  },
  {
    id: '4',
    title: 'Biology for NEET: Complete Guide',
    instructor: 'Dr. Anita Rao',
    instructorAvatar: 'https://i.pravatar.cc/150?img=25',
    thumbnail: 'https://picsum.photos/seed/bio/400/220',
    rating: 4.6,
    reviews: 7600,
    price: 1999,
    originalPrice: 3999,
    enrolled: 54000,
    category: 'Biology',
    level: 'Intermediate',
    duration: '140 hrs',
    lectures: 320,
    description: 'Master Botany and Zoology for NEET with diagrams, MCQs, and revision notes.',
    skills: ['Cell Biology', 'Genetics', 'Ecology', 'Human Physiology', 'Plant Biology'],
    isBestseller: false,
    progress: 0,
    language: 'Hindi + English',
    lastUpdated: 'Nov 2024',
    modules: [],
  },
  {
    id: '5',
    title: 'Full Stack Web Development Bootcamp',
    instructor: 'Rahul Gupta',
    instructorAvatar: 'https://i.pravatar.cc/150?img=30',
    thumbnail: 'https://picsum.photos/seed/webdev/400/220',
    rating: 4.8,
    reviews: 22000,
    price: 4999,
    originalPrice: 9999,
    enrolled: 95000,
    category: 'Coding',
    level: 'Beginner',
    duration: '300 hrs',
    lectures: 650,
    description: 'From HTML basics to React, Node.js, and databases. Build real projects.',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB'],
    isBestseller: true,
    progress: 15,
    language: 'English',
    lastUpdated: 'Jan 2025',
    modules: [],
  },
  {
    id: '6',
    title: 'CAT 2025: Quantitative Aptitude',
    instructor: 'Arun Sharma',
    instructorAvatar: 'https://i.pravatar.cc/150?img=35',
    thumbnail: 'https://picsum.photos/seed/cat/400/220',
    rating: 4.7,
    reviews: 5400,
    price: 3999,
    originalPrice: 7999,
    enrolled: 38000,
    category: 'MBA',
    level: 'Advanced',
    duration: '120 hrs',
    lectures: 280,
    description: 'Crack CAT QA section with shortcuts, tricks, and 5000+ practice questions.',
    skills: ['Arithmetic', 'Algebra', 'Geometry', 'Number Theory', 'Data Interpretation'],
    isBestseller: false,
    progress: 0,
    language: 'English',
    lastUpdated: 'Dec 2024',
    modules: [],
  },
];

export const categories = [
  { id: '1', name: 'Physics', icon: '⚛️', color: '#6C63FF', count: 124 },
  { id: '2', name: 'Mathematics', icon: '📐', color: '#FF6584', count: 98 },
  { id: '3', name: 'Chemistry', icon: '🧪', color: '#43D9AD', count: 86 },
  { id: '4', name: 'Biology', icon: '🧬', color: '#FF8C42', count: 72 },
  { id: '5', name: 'Coding', icon: '💻', color: '#3B82F6', count: 210 },
  { id: '6', name: 'MBA', icon: '📊', color: '#8B5CF6', count: 56 },
  { id: '7', name: 'English', icon: '📚', color: '#EC4899', count: 44 },
  { id: '8', name: 'History', icon: '🏛️', color: '#F59E0B', count: 38 },
];

export const mentors = [
  {
    id: '1',
    name: 'Dr. Nitin Vijay',
    expertise: 'Physics · JEE Expert',
    avatar: 'https://i.pravatar.cc/150?img=11',
    rating: 4.9,
    students: 84500,
    courses: 12,
    experience: '18 years',
    bio: 'Former IIT-Delhi professor with 18 years of teaching experience. Mentored 50,000+ JEE aspirants.',
    tags: ['JEE Advanced', 'NEET', 'Olympiad'],
    sessionPrice: 999,
  },
  {
    id: '2',
    name: 'Anand Kumar',
    expertise: 'Mathematics · Super 30',
    avatar: 'https://i.pravatar.cc/150?img=15',
    rating: 4.9,
    students: 120000,
    courses: 18,
    experience: '22 years',
    bio: 'Founder of Super 30. Transformed mathematics education for underprivileged students across India.',
    tags: ['JEE', 'Competitive Math', 'IIT Prep'],
    sessionPrice: 1499,
  },
  {
    id: '3',
    name: 'Dr. Pradeep Sharma',
    expertise: 'Chemistry · NEET Expert',
    avatar: 'https://i.pravatar.cc/150?img=20',
    rating: 4.8,
    students: 67000,
    courses: 9,
    experience: '15 years',
    bio: 'PhD in Chemistry from IISc Bangalore. Known for simplifying organic chemistry for NEET students.',
    tags: ['NEET', 'Organic Chemistry', 'Board Exams'],
    sessionPrice: 799,
  },
  {
    id: '4',
    name: 'Dr. Anita Rao',
    expertise: 'Biology · NEET Specialist',
    avatar: 'https://i.pravatar.cc/150?img=25',
    rating: 4.7,
    students: 54000,
    courses: 7,
    experience: '12 years',
    bio: 'AIIMS graduate turned educator. Makes complex biological concepts easy with visual learning.',
    tags: ['NEET', 'Biology', 'Zoology'],
    sessionPrice: 699,
  },
  {
    id: '5',
    name: 'Rahul Gupta',
    expertise: 'Web Development · Full Stack',
    avatar: 'https://i.pravatar.cc/150?img=30',
    rating: 4.8,
    students: 95000,
    courses: 15,
    experience: '10 years',
    bio: 'Ex-Google engineer turned educator. Built scalable systems at Google before pursuing his passion for teaching.',
    tags: ['React', 'Node.js', 'System Design'],
    sessionPrice: 1299,
  },
];

export const liveClasses = [
  {
    id: '1',
    title: 'Rotational Motion – Advanced Problems',
    instructor: 'Dr. Nitin Vijay',
    subject: 'Physics',
    time: 'Today, 6:00 PM',
    duration: '90 min',
    enrolled: 2400,
    color: '#6C63FF',
    thumbnail: 'https://picsum.photos/seed/live1/300/160',
  },
  {
    id: '2',
    title: 'Definite Integration Tricks',
    instructor: 'Anand Kumar',
    subject: 'Mathematics',
    time: 'Today, 8:00 PM',
    duration: '120 min',
    enrolled: 3800,
    color: '#FF6584',
    thumbnail: 'https://picsum.photos/seed/live2/300/160',
  },
  {
    id: '3',
    title: 'Organic Chemistry – Reactions Master Class',
    instructor: 'Dr. Pradeep Sharma',
    subject: 'Chemistry',
    time: 'Tomorrow, 5:00 PM',
    duration: '90 min',
    enrolled: 1900,
    color: '#43D9AD',
    thumbnail: 'https://picsum.photos/seed/live3/300/160',
  },
];

export const notifications = [
  { id: '1', type: 'lecture', title: 'New Lecture Uploaded', message: 'Lecture 24: Electromagnetic Induction is now available in Physics Masterclass.', time: '5 min ago', read: false, icon: '🎬' },
  { id: '2', type: 'test', title: 'Test Reminder', message: 'Your weekly test "JEE Mock Test - Series 7" starts in 2 hours.', time: '2 hrs ago', read: false, icon: '📝' },
  { id: '3', type: 'assignment', title: 'Assignment Deadline', message: 'DPP Assignment for Wave Optics is due tomorrow at 11:59 PM.', time: '5 hrs ago', read: true, icon: '⏰' },
  { id: '4', type: 'live', title: 'Live Class Starting Soon', message: 'Dr. Nitin Vijay\'s live class on Rotational Motion starts in 30 minutes.', time: '1 day ago', read: true, icon: '🔴' },
  { id: '5', type: 'result', title: 'Test Result Published', message: 'Your score for Full Syllabus Test 3: 186/360. Rank: 1240.', time: '2 days ago', read: true, icon: '🏆' },
  { id: '6', type: 'offer', title: 'Limited Time Offer!', message: 'Get 50% off on all courses this weekend. Use code: LEARN50', time: '3 days ago', read: true, icon: '🎉' },
];

export const doubts = [
  {
    id: '1',
    student: 'Rahul M.',
    avatar: 'https://i.pravatar.cc/150?img=5',
    subject: 'Physics',
    question: 'In projectile motion, why does the horizontal velocity remain constant throughout the motion?',
    time: '10 min ago',
    likes: 24,
    answers: 3,
    tags: ['Mechanics', 'JEE'],
    answered: true,
  },
  {
    id: '2',
    student: 'Priya S.',
    avatar: 'https://i.pravatar.cc/150?img=6',
    subject: 'Mathematics',
    question: 'How to solve integration by parts when both functions are algebraic? I\'m getting confused with the ILATE rule.',
    time: '25 min ago',
    likes: 18,
    answers: 2,
    tags: ['Calculus', 'Integration'],
    answered: true,
  },
  {
    id: '3',
    student: 'Amit K.',
    avatar: 'https://i.pravatar.cc/150?img=7',
    subject: 'Chemistry',
    question: 'What is the difference between SN1 and SN2 reactions? When does each mechanism apply?',
    time: '1 hr ago',
    likes: 12,
    answers: 0,
    tags: ['Organic', 'NEET'],
    answered: false,
  },
  {
    id: '4',
    student: 'Sneha P.',
    avatar: 'https://i.pravatar.cc/150?img=8',
    subject: 'Biology',
    question: 'Can someone explain the difference between mitosis and meiosis with a clear comparison?',
    time: '3 hrs ago',
    likes: 35,
    answers: 5,
    tags: ['Cell Division', 'NEET'],
    answered: true,
  },
];

export const testSeries = [
  {
    id: '1',
    title: 'JEE Advanced Full Syllabus Mock Test Series 2025',
    totalTests: 30,
    completed: 8,
    duration: '3 hrs',
    subject: 'All Subjects',
    difficulty: 'Hard',
    rating: 4.8,
    attempts: 28000,
    color: '#6C63FF',
    icon: '⚛️',
    price: 1999,
    questions: 90,
  },
  {
    id: '2',
    title: 'NEET Biology Chapter-Wise Test Series',
    totalTests: 45,
    completed: 15,
    duration: '1.5 hrs',
    subject: 'Biology',
    difficulty: 'Medium',
    rating: 4.7,
    attempts: 42000,
    color: '#43D9AD',
    icon: '🧬',
    price: 1499,
    questions: 60,
  },
  {
    id: '3',
    title: 'Mathematics Problem Practice Series',
    totalTests: 25,
    completed: 0,
    duration: '2 hrs',
    subject: 'Mathematics',
    difficulty: 'Hard',
    rating: 4.9,
    attempts: 18000,
    color: '#FF6584',
    icon: '📐',
    price: 999,
    questions: 75,
  },
];

export const quizQuestions = [
  {
    id: 1,
    question: 'A body is projected at an angle of 45° with horizontal. The range is 100m. What is the maximum height reached?',
    options: ['25 m', '50 m', '100 m', '75 m'],
    correct: 0,
    explanation: 'For projectile at 45°, H = R/4 = 100/4 = 25m',
  },
  {
    id: 2,
    question: 'The dimensional formula of electric field intensity is:',
    options: ['[MLT⁻³A⁻¹]', '[ML²T⁻³A⁻¹]', '[MLT⁻²A⁻¹]', '[M⁰LT⁻³A⁻¹]'],
    correct: 0,
    explanation: 'E = F/q, [E] = [MLT⁻²]/[AT] = [MLT⁻³A⁻¹]',
  },
  {
    id: 3,
    question: 'Which of the following is NOT a property of electric field lines?',
    options: ['They start from positive charges', 'They can form closed loops', 'They never intersect each other', 'They end at negative charges'],
    correct: 1,
    explanation: 'Electric field lines cannot form closed loops. Only magnetic field lines can form closed loops.',
  },
  {
    id: 4,
    question: 'The moment of inertia of a solid sphere about its diameter is:',
    options: ['(2/5)MR²', '(2/3)MR²', 'MR²', '(1/2)MR²'],
    correct: 0,
    explanation: 'For solid sphere, I = 2MR²/5 about any diameter.',
  },
  {
    id: 5,
    question: 'In a P-N junction diode, the barrier potential is due to:',
    options: ['Donor and acceptor ions', 'Free electrons only', 'Holes only', 'Majority carriers'],
    correct: 0,
    explanation: 'The barrier potential is due to the fixed donor and acceptor ions at the junction.',
  },
];

export const onboardingData = [
  {
    id: 1,
    title: 'Learn From Anywhere',
    subtitle: 'Access 10,000+ courses anytime, anywhere on your phone. Download lectures for offline learning.',
    emoji: '🌍',
    gradient: ['#6C63FF', '#8B84FF'],
  },
  {
    id: 2,
    title: 'Expert Mentors',
    subtitle: 'Learn from India\'s top educators — IIT professors, industry experts, and coaching legends.',
    emoji: '👨‍🏫',
    gradient: ['#FF6584', '#FF8FA3'],
  },
  {
    id: 3,
    title: 'Practice & Succeed',
    subtitle: 'Sharpen your skills with daily practice problems, mock tests, and AI-powered performance analysis.',
    emoji: '🏆',
    gradient: ['#43D9AD', '#6EE7C0'],
  },
];